### ISSUE TITLE
Add transform for converting geo point data (lat, lng) to GeoJSON array

### ISSUE THREAD

**Issue by willium** [vega/vega-geo#2]
It would be extremely useful for vega-lite's geo implementation for Vega to include a new transform to convert geo point data into GeoJSON data. That way, the fit and size properties of `projection` can be used with all geo data.

**Comment by willium** [comment]
Happy to write this transform myself, but was curious if this is something that might be folded into the existing geo-point transform or would be better as its own transform or even an expression.

**Comment by jheer** [comment]
I think this most likely makes sense as a transform parameterized by two field accessors (one for longitude, one for latitude). It then processes a tuple stream to construct a single GeoJSON object that includes all data points. This resulting object would be saved as the `value` property of the transform.

An open question is if the transform should then pass along the underlying data stream untouched, or generate a new data stream with the constructed GeoJSON object as the sole member. The former is simpler in that it could be embedded within a standard transform pipeline. The latter would require a separate data source, but would allow one to use the GeoJSON elsewhere in Vega. I think I would lean to an initial implementation using the former strategy; we could always change / expand later if warranted...

**Comment by willium** [comment]
Ah that second question is interesting. I think the former might make more sense as well. 
A couple follow-up questions, for someone with a much better understanding of edge cases:
1. Is there any utility in this beyond use in `projection`'s fit property? 
1. Could one forego a `geo-point` transform in favor of a `geo-shape` transform or `geo-path` transform after doing this conversion?

**Comment by domoritz** [comment]
Would it make sense to implement lat + long -> geojson as an expression rather than a separate transform?

**Comment by jheer** [comment]
Yes, that's one option. From a Vega perspective it's cleaner / more flexible to implement a data transform (whose value could be bound to a signal). I think I would prefer that approach. But, if it is dramatically easier to invoke a data source dependent expression in Vega-Lite I _might_ be convinced.

**Comment by jheer** [comment]
@willium In answer to your question, the utility beyond projection `fit` would be if a transform produced a new tuple (containing a GeoJSON point collection) as an output data stream. It could then be visualized using `geoshape` or `geopath`. In that case one would probably need to include a size field (to set circular size) as well to make that configurable. The fill/stroke color would be uniform for all data points and they would be treated as a single object from an interaction perspective. So there are some serious limitations and so I don't think it adds much beyond using `geopoint` and standard encodings (other than a potential small rendering performance boost).

That's why I lean towards a transform that lets the original data tuples pass through, but sets the transform `value` to the GeoJSON collection as a "side effect".

**Comment by willium** [comment]
We're planning on extending the `geojson` transform I'm working on for this issue to also support aggregating a non-GeoJSON data set with a data field containing GeoJSON data into a GeoJSON data set (array) composed of the value of that field across the original data (also as a side effect, also for `fit`). Therefore, one using the transform might need to specify:

`fields` for `latitude` and `longitude` (for conversion into geojson geopoints) 
xor 
a `field` for the data field containing GeoJSON data. 

In the spirit of consistency with the `geopoint` transform, I was thinking a transform of the form
```
{
  "type": "geojson",
  "fields": ["lon", "lat"],
  "signal": "outputGeoJSON"
}
```
would make the most sense when it was only lon/lat we were converting to GeoJSON. Now, because we might be instead converting based on one field instead of a tuple of fields, I'm considering one of the following forms for the transform:
1. 
   ```
   {
     "type": "geojson",
     "fields": ["lon", "lat"] | ["geom"],
     "signal": "outputGeoJSON"
   }
   ```

2. 
   ```
   {
     "type": "geojson",
     "fields"?: ["lon", "lat"],
     "field"?: "geom",
     "signal": "outputGeoJSON"
   }
   // one would only specify "fields" or "field" not both.
   // "field" could be renamed to "geometry", or "fields" could be renamed to "coordinates", or both, or something similar
   ```

3. 
   ```
   {
     "type": "geojson",
     "latitude"?: "lat",
     "longitude"?: "long",
     "geometry"?: "geom",
     "signal": "outputGeoJSON"
   }
   // one would only specify "latitude" and "longitude" OR "geometry".
   // less consistent with geopoint
   ```
Not _loving_ any of these options, wondering if you had any suggestions.

**Comment by willium** [comment]
@domoritz prefers 1 or 2. I prefer 1, I think.

**Comment by jheer** [comment]
How about `fields` for lon/lat coords and a `geojson` param for the other? That maintains consistency with `GeoPoint` while also using a more interpretable name for the second option.

Other observations:

1. The two params don't have to be mutually exclusive. The transform could handle both in one shot.
2. The Projection transform's fit param already aggregates singular GeoJSON values into a FeatureCollection. If the new param is needed for your new transform, we might try to reuse code across transforms for similar tasks...

**Comment by willium** [comment]
I like the idea of a fields param and a geojson param. I incorporated that and your observations into the PR. However, when testing the code with my Vega spec, I found that, while the transform seems to work as expected (it produces a feature collection), Vega (or really, D3) crashes the browser when running "fit" on it. I wonder if I'm making a mistake at some point in the process, or if not, there is a way to optimize the geojson better during the transform.

**Comment by jheer** [comment]
Sounds like you should export the generated GeoJSON and test it separately? Is it possible that it deviates from the GeoJSON spec in some way? Can you identify where in the D3 code it might be hitting an infinite loop? (I assume that's what you mean by "crashes the browser"? If so, make sure there is not some self-reference within the generated GeoJSON object; you can test that by trying to run it through `JSON.stringify`.)

**Comment by willium** [comment]
It does indeed sound like I have some self-reference within the GeoJSON. I'll figure it out this evening.
