### ISSUE TITLE
Contour transform does not work using "values"

### ISSUE THREAD

**Issue by sparkofreason** [vega/vega-geo#8]
Using the contour transform specifying values rather than using kernel density estimation yields the following errors in the browser console log:

logger.js:3 ERROR TypeError: n[t] is not a function
    at Contour.js:77
    at Array.forEach (<anonymous>)
    at r.Object.transform (Contour.js:76)
    at r.o.evaluate (Transform.js:52)
    at r.o.run (Transform.js:33)
    at r [as run] (run.js:60)
    at r.x.run (View.js:97)
    at t.value (renderer.tsx:40)
    at t.value (renderer.tsx:73)
    at commitLifeCycles (react-dom.production.min.js:149)
r @ logger.js:3
error @ logger.js:24
(anonymous) @ Dataflow.js:111
r @ run.js:90
x.run @ View.js:97
value @ renderer.tsx:40
value @ renderer.tsx:73
commitLifeCycles @ react-dom.production.min.js:149
t @ react-dom.production.min.js:158
_ @ react-dom.production.min.js:169
O @ react-dom.production.min.js:168
batchedUpdates @ react-dom.production.min.js:171
Z @ react-dom.production.min.js:54
De @ react-dom.production.min.js:71
logger.js:3 ERROR TypeError: Cannot read property 'marktype' of undefined
    at r.h.draw (CanvasRenderer.js:104)
    at group.js:84
    at a (visit.js:35)
    at group.js:83
    at a (visit.js:35)
    at r.s (group.js:47)
    at r.h.draw (CanvasRenderer.js:106)
    at group.js:84
    at a (visit.js:35)
    at group.js:83
r @ logger.js:3
error @ logger.js:24
(anonymous) @ Dataflow.js:111
x.run @ View.js:102
value @ renderer.tsx:40
value @ renderer.tsx:73
commitLifeCycles @ react-dom.production.min.js:149
t @ react-dom.production.min.js:158
_ @ react-dom.production.min.js:169
O @ react-dom.production.min.js:168
batchedUpdates @ react-dom.production.min.js:171
Z @ react-dom.production.min.js:54
De @ react-dom.production.min.js:71

Repro data may be found at:

https://gist.github.com/sparkofreason/19491934f3a50f8e0297d0249059d39d

**Comment by jheer** [comment]
Thank you for reporting this! This issue has been fixed in vega-geo v2.2.2, and will be included in the next Vega release.
